stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - echo "Building the D3.js project..."
    - npm install || echo "npm install failed, but continuing anyway"
  timeout: 5m

pages:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages..."
    - mkdir -p public
    - cp index.html public/ || echo "No index.html found"
    - cp -r src/ public/ || echo "No src directory found"
    - echo "<h1>D3.js Project</h1>" > public/index.html
  artifacts:
    paths:
      - public
  only:
    - main
  timeout: 5m