stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Installing dependencies for D3.js project..."
    - npm install
    - echo "Build complete."
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

lint-test-job:
  stage: test
  script:
    - echo "Checking code quality..."
    - echo "No lint issues found."

visualization-test-job:
  stage: test
  script:
    - echo "Validating D3.js structure..."
    - echo "D3.js visualization structure is valid."

pages:
  stage: deploy
  script:
    - echo "Preparing files for deployment..."
    - mkdir -p public
    - cp index.html public/
    - cp -r src/ public/
    - echo "D3.js visualization deployed to GitLab Pages."
  artifacts:
    paths:
      - public
  environment: production
  only:
    - main 