image: node:18-alpine

stages:
  - build
  - deploy

default:
  tags:
    - docker 

build-job:
  stage: build
  script:
    - echo "Building the D3.js project..."
    - npm install
    - if npm run build; then echo "Build successful"; else echo "Build script missing!"; exit 1; fi
  artifacts:
    paths:
      - dist/
  timeout: "5m"

pages:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages..."
    - mkdir -p public
    - cp -r dist/* public/ || echo "No build output found"
  artifacts:
    paths:
      - public
  only:
    - main
  timeout: 5m
